// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 3/21/2025, 2:38:36 AM
const configMerger = require("C:/Users/USER/Desktop/projects/Bickey/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/USER/Desktop/projects/Bickey/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/plugins/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bickey/composables/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bickey/utils/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bickey/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bickey/app.config.{js,ts,mjs}"] } }));

module.exports = config
