// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/11/2025, 7:48:22 AM
const configMerger = require("C:/Users/USER/Desktop/projects/Bestbuy/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [

].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["C:/Users/USER/Desktop/projects/Bestbuy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/plugins/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bestbuy/composables/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bestbuy/utils/**/*.{js,ts,mjs}","C:/Users/USER/Desktop/projects/Bestbuy/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/USER/Desktop/projects/Bestbuy/app.config.{js,ts,mjs}"] } }));

module.exports = config
